version: v0.6.0-alpha.1

log:
  level: debug

namespaces:
  - id: 0
    name: videos

dsn: postgres://root:secret@postgresd:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
